In [1]:
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)
print(keras.__version__)

/home/sfefilatyev/projects/tensorflow_exercises/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sfefilatyev/projects/tensorflow_exercises/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sfefilatyev/projects/tensorflow_exercises/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int1

2.0.0-beta1
2.2.4-tf


In [32]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()
print(X_train_full.shape)
print(X_train_full.dtype)
print(y_train_full.shape)
print(y_train_full.dtype)
print(X_test.shape)
print(X_test.dtype)

(60000, 28, 28)
uint8
(60000,)
uint8
(10000, 28, 28)
uint8


In [13]:
import numpy as np
from pprint import pprint

In [33]:
A_indices = np.where(y_train_full<8)
B_indices = np.where(y_train_full>=8)

X_train_full_A = X_train_full[A_indices]
X_train_full_B = X_train_full[B_indices]

y_train_full_A = y_train_full[A_indices]
y_train_full_B = y_train_full[B_indices]

print("size A = {}".format(len(y_train_full_A)))
print("size B = {}".format(len(y_train_full_B)))

size A = 48000
size B = 12000


In [74]:
A_indices_test = np.where(y_test<8)
B_indices_test = np.where(y_test>=8)

y_test_A = y_test[A_indices_test]
y_test_B = y_test[B_indices_test]
y_test_B = y_test_B - 8

X_test_A = X_test[A_indices_test] / 255.0
X_test_B = X_test[B_indices_test] / 255.0

pprint(y_test[:100])
pprint("len y_test_A = {}".format(len(y_test_A)))
pprint("len y_test_B = {}".format(len(y_test_B)))
pprint(y_test_A[:100])
pprint(y_test_B[:100])

array([9, 2, 1, 1, 6, 1, 4, 6, 5, 7, 4, 5, 7, 3, 4, 1, 2, 4, 8, 0, 2, 5,
       7, 9, 1, 4, 6, 0, 9, 3, 8, 8, 3, 3, 8, 0, 7, 5, 7, 9, 6, 1, 3, 7,
       6, 7, 2, 1, 2, 2, 4, 4, 5, 8, 2, 2, 8, 4, 8, 0, 7, 7, 8, 5, 1, 1,
       2, 3, 9, 8, 7, 0, 2, 6, 2, 3, 1, 2, 8, 4, 1, 8, 5, 9, 5, 0, 3, 2,
       0, 6, 5, 3, 6, 7, 1, 8, 0, 1, 4, 2], dtype=uint8)
'len y_test_A = 8000'
'len y_test_B = 2000'
array([2, 1, 1, 6, 1, 4, 6, 5, 7, 4, 5, 7, 3, 4, 1, 2, 4, 0, 2, 5, 7, 1,
       4, 6, 0, 3, 3, 3, 0, 7, 5, 7, 6, 1, 3, 7, 6, 7, 2, 1, 2, 2, 4, 4,
       5, 2, 2, 4, 0, 7, 7, 5, 1, 1, 2, 3, 7, 0, 2, 6, 2, 3, 1, 2, 4, 1,
       5, 5, 0, 3, 2, 0, 6, 5, 3, 6, 7, 1, 0, 1, 4, 2, 3, 6, 7, 2, 7, 5,
       4, 2, 5, 7, 0, 5, 2, 6, 7, 0, 0, 3], dtype=uint8)
array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,

In [75]:
X_valid_A, X_train_A = X_train_full_A[:4000] / 255.0, X_train_full_A[4000:] / 255.0
y_valid_A, y_train_A = y_train_full_A[:4000], y_train_full_A[4000:]

X_valid_B, X_train_B = X_train_full_B[:1000] / 255.0, X_train_full_B[1000:] / 255.0
y_valid_B, y_train_B = y_train_full_B[:1000], y_train_full_B[1000:]

y_train_B = y_train_B - 8
y_valid_B = y_valid_B - 8

pprint(y_train_B[:100])
pprint(y_valid_B[:100])

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1], dtype=uint8)
array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1], dtype=uint8)


In [35]:
class_names_A = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker"]
class_names_B = ["Bag", "Ankle boot"]

In [36]:
model_A = keras.models.Sequential()
model_A.add(keras.layers.Flatten(input_shape=[28, 28]))
model_A.add(keras.layers.Dense(300, activation="relu"))
model_A.add(keras.layers.Dense(100, activation="relu"))
model_A.add(keras.layers.Dense(8, activation="softmax"))
print(model_A.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 300)               235500    
_________________________________________________________________
dense_4 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 808       
Total params: 266,408
Trainable params: 266,408
Non-trainable params: 0
_________________________________________________________________
None


In [37]:
model_A.compile(loss="sparse_categorical_crossentropy", optimizer="Adam", metrics=["accuracy"])

In [38]:
history = model_A.fit(X_train_A, y_train_A, epochs=30, validation_data=(X_valid_A, y_valid_A))

Train on 44000 samples, validate on 4000 samples
Epoch 1/30
44000/44000 [==============================] - 3s 63us/sample - loss: 0.5055 - accuracy: 0.8141 - val_loss: 0.4157 - val_accuracy: 0.8462
Epoch 2/30
44000/44000 [==============================] - 2s 52us/sample - loss: 0.3922 - accuracy: 0.8511 - val_loss: 0.3710 - val_accuracy: 0.8640
Epoch 3/30
44000/44000 [==============================] - 2s 53us/sample - loss: 0.3534 - accuracy: 0.8657 - val_loss: 0.3687 - val_accuracy: 0.8615
Epoch 4/30
44000/44000 [==============================] - 2s 53us/sample - loss: 0.3323 - accuracy: 0.8740 - val_loss: 0.3329 - val_accuracy: 0.8770
Epoch 5/30
44000/44000 [==============================] - 2s 55us/sample - loss: 0.3156 - accuracy: 0.8814 - val_loss: 0.3473 - val_accuracy: 0.8662
Epoch 6/30
44000/44000 [==============================] - 2s 55us/sample - loss: 0.3012 - accuracy: 0.8855 - val_loss: 0.3532 - val_accuracy: 0.8698
Epoch 7/30
44000/44000 [==============================] -

In [43]:
model_A.evaluate(X_test_A, y_test_A)

8000/8000 [==============================] - 0s 23us/sample - loss: 2.4109 - accuracy: 0.8491


[2.410911674499511, 0.849125]

In [76]:
model_A_clone = keras.models.clone_model(model_A)
model_A_clone.set_weights(model_A.get_weights())
model_B_on_A = keras.models.Sequential(model_A.layers[:-1])
model_B_on_A.add(keras.layers.Dense(1, activation='sigmoid'))
for layer in model_B_on_A.layers[:-1]:
    layer.trainable = False

model_B_on_A.compile(loss="binary_crossentropy", optimizer="Adam", metrics=["accuracy"])

In [77]:
history = model_B_on_A.fit(X_train_B, y_train_B, epochs=4, validation_data=(X_valid_B, y_valid_B))
for layer in model_B_on_A.layers[:-1]:
    layer.trainable = True
    
optimizer = keras.optimizers.Adam(lr=1e-4)
model_B_on_A.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=["accuracy"])
history = model_B_on_A.fit(X_train_B, y_train_B, epochs=16, validation_data=(X_valid_B, y_valid_B))

Train on 11000 samples, validate on 1000 samples
Epoch 1/4
11000/11000 [==============================] - 1s 48us/sample - loss: 0.7981 - accuracy: 0.8061 - val_loss: 0.0609 - val_accuracy: 0.9880
Epoch 2/4
11000/11000 [==============================] - 0s 38us/sample - loss: 0.0471 - accuracy: 0.9892 - val_loss: 0.0240 - val_accuracy: 0.9950
Epoch 3/4
11000/11000 [==============================] - 0s 38us/sample - loss: 0.0232 - accuracy: 0.9943 - val_loss: 0.0153 - val_accuracy: 0.9970
Epoch 4/4
11000/11000 [==============================] - 0s 37us/sample - loss: 0.0154 - accuracy: 0.9959 - val_loss: 0.0116 - val_accuracy: 0.9970
Train on 11000 samples, validate on 1000 samples
Epoch 1/16
11000/11000 [==============================] - 1s 80us/sample - loss: 0.0053 - accuracy: 0.9983 - val_loss: 0.0052 - val_accuracy: 0.9980
Epoch 2/16
11000/11000 [==============================] - 1s 54us/sample - loss: 0.0024 - accuracy: 0.9993 - val_loss: 0.0054 - val_accuracy: 0.9990
Epoch 3/16
1

In [78]:
pprint(y_valid_B[:100])

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1], dtype=uint8)
